const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
class Element{
 constructor(){this.children=[];this.listeners={};this.dataset={};this.open=false;this.classList={add(){},remove(){},toggle(){}};}
 append(...nodes){this.children.push(...nodes);} prepend(...nodes){this.children.unshift(...nodes);} replaceChildren(...nodes){this.children=nodes;} setAttribute(){} focus(){} showModal(){this.open=true;} close(){this.open=false;} addEventListener(name,handler){this.listeners[name]=handler;} contains(node){return this===node||this.children.some(child=>child.contains(node));}
}
const elements=new Map(),calls=[],handlers={},events={};let heldEdit=null,heldSettings=null;
let state={registers:['one\r\ntwo\n世界',...Array(25).fill(null)],registerNames:['Named',...Array(25).fill('')],history:['history\n世界\nfull'],currentClipboard:'current',selection:null,copy:false,status:'Ready'};
const document={getElementById(id){if(!elements.has(id))elements.set(id,new Element());return elements.get(id);},createElement(){return new Element();},querySelectorAll(){return[];},addEventListener(name,fn){events[name]=fn;}};
const window={__TAURI__:{core:{invoke:async(name,args)=>{calls.push({name,args});if(name==='edit_register'&&heldEdit)return heldEdit;if(name==='save_hotkeys'){if(heldSettings)return heldSettings;state.hotkeys=args.hotkeys;return args.hotkeys;}return state;}},event:{listen:async(name,fn)=>{handlers[name]=fn;}}}};
vm.runInNewContext(fs.readFileSync(__dirname+'/../ui/app.js','utf8'),{document,window,TextEncoder,setTimeout});
const $=id=>elements.get(id),tick=()=>new Promise(resolve=>setImmediate(resolve));
const row=()=>$('registers').children[0],cell=()=>row().children[0],box=()=>cell().children[0];
const outside=()=>{events.pointerdown({target:new Element()});events.click();};
const setHotkey=(action,shortcut)=>{const parts=shortcut.split('+');for(const [id,token] of [['ctrl','Ctrl'],['alt','Alt'],['shift','Shift'],['super','Super']])$(`hotkey-${action}-${id}`).checked=parts.includes(token);$(`hotkey-${action}-key`).value=parts.at(-1);$(`hotkey-${action}-key`).listeners.change();};
(async()=>{await tick();
 const source=$('history').children[0],data={types:['text/plain'],setData(type,text){this.text=text;},getData(){return this.text;}};
 source.listeners.dragstart({dataTransfer:data});assert.equal(data.text,state.history[0]);
 handlers['clipforge-state']({payload:{...state,history:['new',...state.history]}});assert.equal($('history').children[0],source);
 await $('registers').children[23].listeners.drop({preventDefault(){},dataTransfer:data});assert.equal(calls.at(-1).name,'save_text');assert.equal(calls.at(-1).args.text,state.history[0]);source.listeners.dragend();
 await cell().children[0].listeners.click();assert.equal(calls.at(-1).name,'set_clipboard');assert.equal(calls.at(-1).args.text,state.registers[0]);
 assert.equal(box().children[0].value,'Named');assert.equal(box().children[1].value,state.registers[0]);
 box().children[0].value='New name';box().children[1].value=' exact\n世界\n';outside();await tick();
 let saved=calls.findLast(call=>call.name==='edit_register');assert.equal(saved.args.name,'New name');assert.equal(saved.args.text,' exact\n世界\n');assert.equal(calls.at(-1).name,'end_edit');
 await cell().children[0].listeners.click();box().children[1].value='saved before history';
 const historyTarget=$('history').children[0];events.pointerdown({target:historyTarget});await tick();assert.equal($('history').children[0],historyTarget,'autosave preserves pending click target');await historyTarget.listeners.click();events.click();await new Promise(resolve=>setTimeout(resolve,5));
 const tail=calls.slice(-3).map(call=>call.name);assert.deepEqual(tail,['edit_register','end_edit','set_clipboard']);
 await cell().children[0].listeners.click();box().children[0].value='x'.repeat(81);outside();await tick();assert.ok(box().children[3].textContent.includes('80'));assert.equal(calls.at(-1).name,'set_clipboard');
 handlers['clipforge-cancel-edit']();assert.equal(calls.at(-1).name,'end_edit');
 await cell().children[0].listeners.click();box().children[1].value='discard';events.keydown({key:'Escape',preventDefault(){}});assert.equal(calls.at(-1).name,'end_edit');
 await cell().children[0].listeners.click();box().children[1].value=state.registers[0].replace(/\r\n?/g,'\n');const before=calls.filter(call=>call.name==='edit_register').length;outside();await tick();assert.equal(calls.filter(call=>call.name==='edit_register').length,before,'unchanged normalized line endings do not write');
 await row().children[1].listeners.click();assert.equal(calls.at(-1).name,'clear_register');
 await $('current-clipboard').listeners.drop({preventDefault(){},dataTransfer:data});assert.equal(calls.at(-1).name,'set_clipboard');assert.equal(calls.at(-1).args.text,state.history[0]);
 await $('current-clipboard').listeners.click({target:$('current-preview')});const currentBox=$('current-preview').children[0];currentBox.children[0].value='edited current\n世界';outside();await tick();assert.equal(calls.findLast(call=>call.name==='set_clipboard').args.text,'edited current\n世界');
 await cell().children[0].listeners.click();box().children[1].value='save before dragging';
 const dragHistory=$('history').children[0];events.pointerdown({target:dragHistory});
 let prevented=false;dragHistory.listeners.dragstart({dataTransfer:data,preventDefault(){prevented=true;}});assert.equal(prevented,false,'history drag works while register autosave runs');
 await $('current-clipboard').listeners.drop({preventDefault(){},dataTransfer:data});
 assert.equal(calls.findLast(call=>call.name==='edit_register').args.text,'save before dragging');
 handlers['clipforge-state']({payload:{...state,currentClipboard:'latest drag clipboard',status:'Drag done'}});
 dragHistory.listeners.dragend();assert.equal($('current-preview').textContent,'latest drag clipboard','drag end clears pointer deferral without a click');
 await cell().children[0].listeners.click();const activeBox=box();activeBox.children[1].value='pending write';
 let rejectEdit;heldEdit=new Promise((resolve,reject)=>{rejectEdit=reject;});const endCount=calls.filter(call=>call.name==='end_edit').length;
 outside();await tick();assert.equal(activeBox.children[1].disabled,true);assert.equal(activeBox.children[0].disabled,true);
 events.keydown({key:'Escape',preventDefault(){}});assert.equal(box(),activeBox,'Escape does not destroy editor during a pending write');
 rejectEdit(new Error('clipboard write failed'));await tick();heldEdit=null;
 assert.equal(box(),activeBox);assert.equal(activeBox.children[1].disabled,false);assert.equal(activeBox.children[0].disabled,false);assert.ok(activeBox.children[3].textContent.includes('failed'));assert.equal(calls.filter(call=>call.name==='end_edit').length,endCount,'failed pending write retains pin');
 activeBox.children[0].value='Submitted name';activeBox.children[1].value='submitted register';
 let stopped=false;await activeBox.children[4].listeners.click({stopPropagation(){stopped=true;}});
 assert.equal(stopped,true,'submit cannot bubble into another editor');assert.equal(calls.findLast(call=>call.name==='edit_register').args.text,'submitted register');assert.equal(calls.findLast(call=>call.name==='edit_register').args.name,'Submitted name');assert.equal(calls.at(-1).name,'end_edit');
 await $('current-clipboard').listeners.click({target:$('current-preview')});const submittedCurrent=$('current-preview').children[0];submittedCurrent.children[0].value='submitted clipboard';
 await submittedCurrent.children[3].listeners.click({stopPropagation(){}});assert.equal(calls.findLast(call=>call.name==='set_clipboard').args.text,'submitted clipboard');assert.equal(calls.at(-1).name,'end_edit');
 await cell().children[0].listeners.click();box().children[1].value='saved before menu toggle';
 await handlers['clipforge-toggle']();assert.equal(calls.findLast(call=>call.name==='edit_register').args.text,'saved before menu toggle');assert.equal(calls.at(-1).name,'dismiss');assert.equal(calls.at(-1).args.commit,false);
 await cell().children[0].listeners.click();box().children[0].value='x'.repeat(81);const dismissCount=calls.filter(call=>call.name==='dismiss').length;
 await handlers['clipforge-toggle']();assert.equal(calls.filter(call=>call.name==='dismiss').length,dismissCount,'invalid edit keeps menu open when toggled');
 handlers['clipforge-cancel-edit']();
 events.keydown({key:'Enter',target:{matches(){return false;}},preventDefault(){}});await tick();assert.equal(calls.at(-1).name,'dismiss');assert.equal(calls.at(-1).args.commit,true,'Enter loads the highlighted entry without modifier-release dismissal');
 await $('save-current').onclick();assert.equal($('save-dialog').open,true);await handlers['clipforge-toggle']();assert.equal($('save-dialog').open,false,'toggle closes the register-letter dialog');assert.equal(calls.at(-1).name,'dismiss');
 await handlers['clipforge-blur']();assert.equal(calls.at(-1).name,'dismiss_on_blur','idle outside dismissal uses the command that leaves focus outside');
 await cell().children[0].listeners.click();box().children[1].value='save before outside click';
 await handlers['clipforge-blur']();assert.deepEqual(calls.slice(-3).map(call=>call.name),['edit_register','end_edit','dismiss_on_blur'],'outside dismissal waits for the editor to save');
 await cell().children[0].listeners.click();box().children[0].value='x'.repeat(81);const blurDismissCount=calls.filter(call=>call.name==='dismiss_on_blur').length;
 await handlers['clipforge-blur']();assert.equal(calls.filter(call=>call.name==='dismiss_on_blur').length,blurDismissCount,'outside dismissal preserves invalid edits');handlers['clipforge-cancel-edit']();
 await $('save-current').onclick();await handlers['clipforge-blur']();assert.equal($('save-dialog').open,false,'outside click closes the register-letter chooser');assert.equal(calls.at(-1).name,'dismiss_on_blur');
 await cell().children[0].listeners.click();box().children[1].value='save before settings';
 await $('settings').onclick();assert.equal($('settings-dialog').open,true);assert.equal(calls.findLast(call=>call.name==='edit_register').args.text,'save before settings');
 assert.equal($('hotkey-menu-key').value,'Space');assert.equal($('hotkey-menu-ctrl').checked,true);assert.equal($('hotkey-menu-alt').checked,true);assert.equal($('hotkey-menu-preview').textContent,'Ctrl+Alt+Space');
 assert.equal($('hotkey-menu-key').children[0].children[0].textContent,'Spacebar (Space)','Space has an explicit dropdown label');
 const settingsCalls=calls.filter(call=>call.name==='save_hotkeys').length;
 setHotkey('menu','Shift+Space');await $('settings-form').onsubmit({preventDefault(){}});assert.equal($('settings-dialog').open,true);assert.ok($('settings-error').textContent.includes('select Ctrl'));assert.equal(calls.filter(call=>call.name==='save_hotkeys').length,settingsCalls);
 setHotkey('menu','Ctrl+Alt+ ');await $('settings-form').onsubmit({preventDefault(){}});assert.ok($('settings-error').textContent.includes('dropdown'));assert.equal(calls.filter(call=>call.name==='save_hotkeys').length,settingsCalls,'literal whitespace cannot become an activation key');
 setHotkey('menu','Ctrl+Shift+F12');assert.equal($('hotkey-menu-preview').textContent,'Ctrl+Shift+F12');
 await $('settings-form').onsubmit({preventDefault(){}});assert.equal($('settings-dialog').open,false);assert.equal($('menu-shortcut').textContent,'Ctrl+Shift+F12');assert.equal(calls.at(-1).name,'end_edit');
 await $('settings').onclick();setHotkey('menu','Ctrl+Alt+F11');
 let rejectSettings;heldSettings=new Promise((resolve,reject)=>{rejectSettings=reject;});
 const hideCount=calls.filter(call=>call.name==='dismiss_on_blur').length;
 const blur=handlers['clipforge-blur']();await tick();assert.equal($('settings-submit').disabled,true);assert.equal($('hotkey-menu-key').disabled,true);assert.equal($('hotkey-menu-ctrl').disabled,true);
 await $('settings-cancel').onclick();assert.equal($('settings-dialog').open,true,'pending save cannot be cancelled');
 rejectSettings(new Error('Shortcut already owned'));await blur;heldSettings=null;
 assert.equal($('settings-dialog').open,true);assert.equal($('hotkey-menu-key').value,'F11');assert.equal($('settings-submit').disabled,false);assert.equal($('hotkey-menu-key').disabled,false);assert.ok($('settings-error').textContent.includes('owned'));assert.equal(calls.filter(call=>call.name==='dismiss_on_blur').length,hideCount,'settings error prevents hiding');
 await $('settings-form').onsubmit({preventDefault(){}});assert.equal($('settings-dialog').open,false);
 await $('settings').onclick();$('settings-defaults').onclick();assert.equal($('hotkey-menu-key').value,'Space');assert.equal($('hotkey-menu-preview').textContent,'Ctrl+Alt+Space');await $('settings-cancel').onclick();assert.equal(state.hotkeys.menu,'Ctrl+Alt+F11','cancel discards restored defaults');
 await $('settings').onclick();setHotkey('copy','Alt+Shift+F10');setHotkey('paste','Ctrl+Super+9');assert.equal($('hotkey-paste-preview').textContent,'Ctrl+Win / Command+9');await handlers['clipforge-toggle']();assert.equal(state.hotkeys.copy,'Alt+Shift+F10');assert.equal(state.hotkeys.paste,'Ctrl+Super+9');assert.equal(calls.at(-1).name,'dismiss');
 await cell().children[0].listeners.click();box().children[1].value='save before tray quit';await handlers['clipforge-quit']();assert.equal(calls.findLast(call=>call.name==='edit_register').args.text,'save before tray quit');assert.equal(calls.at(-1).name,'quit');
 await cell().children[0].listeners.click();box().children[1].value='save before clearing history';
 await $('clear-history').onclick();assert.deepEqual(calls.slice(-3).map(call=>call.name),['edit_register','end_edit','clear_history']);
 handlers['clipforge-state']({payload:{...state,history:[]}});assert.equal($('count').textContent,'0 items');assert.equal($('registers').children.length,26);
 await $('clear').onclick();assert.equal(calls.at(-1).name,'clear_all');
 console.log('PASS: inline edits, autosave, focus loss, validation retention, history, drag/drop, settings, tray quit, separate history clearing');
})().catch(error=>{console.error(error);process.exitCode=1;});
